/*
 * ISP_ConfigManager.cpp - ISP配置管理器实现
 * 管理ISP参数配置和配置文件读写
 * 阶段三：ISP配置界面开发 - 参数管理
 */

#include "ISP_ConfigManager.h"

// 构造函数
ISPConfigManager::ISPConfigManager() 
    : m_sdCardManager(nullptr)
{
    initDefaultConfig();
}

// 初始化默认配置
void ISPConfigManager::initDefaultConfig() {
    defaultConfig.exposureMode = ISP_EXPOSURE_MODE_DEFAULT;
    defaultConfig.brightness = ISP_BRIGHTNESS_DEFAULT;
    defaultConfig.contrast = ISP_CONTRAST_DEFAULT;
    defaultConfig.saturation = ISP_SATURATION_DEFAULT;
    defaultConfig.awbMode = ISP_AWB_MODE_DEFAULT;

    currentConfig = defaultConfig;
}

// 初始化配置管理器
bool ISPConfigManager::init(SDCardManager& sdCardManager) {
    if (initialized) {
        Utils_Logger::info("ISPConfigManager already initialized");
        return true;
    }

    m_sdCardManager = &sdCardManager;
    
    Utils_Logger::info("Initializing ISPConfigManager...");

    // 尝试从文件加载配置
    if (!loadConfig()) {
        Utils_Logger::info("Failed to load config, using defaults");
    }

    initialized = true;
    Utils_Logger::info("ISPConfigManager initialized successfully");
    return true;
}

// 从文件加载配置
bool ISPConfigManager::loadConfig() {
    if (!m_sdCardManager || !m_sdCardManager->isInitialized()) {
        Utils_Logger::info("SD card manager not initialized");
        return false;
    }

    if (!m_sdCardManager->fileExists(ISP_CONFIG_FILE_PATH)) {
        Utils_Logger::info("Config file not found: %s", ISP_CONFIG_FILE_PATH);
        return false;
    }

    Utils_Logger::info("Loading config from: %s", ISP_CONFIG_FILE_PATH);

    AmebaFatFS* fs = m_sdCardManager->getFileSystem();
    if (!fs) {
        Utils_Logger::error("Failed to get file system");
        return false;
    }

    File configFile = fs->open(ISP_CONFIG_FILE_PATH);
    if (!configFile) {
        Utils_Logger::error("Failed to open config file");
        return false;
    }

    String line;
    while (configFile.available()) {
        line = configFile.readStringUntil('\n');
        line.trim();

        if (line.length() == 0 || line.startsWith("#")) {
            continue;
        }

        int equalsPos = line.indexOf('=');
        if (equalsPos > 0) {
            String key = line.substring(0, equalsPos);
            String valueStr = line.substring(equalsPos + 1);
            int value = valueStr.toInt();

            if (key == "EXPOSURE_MODE") {
                currentConfig.exposureMode = value;
            } else if (key == "BRIGHTNESS") {
                currentConfig.brightness = value;
            } else if (key == "CONTRAST") {
                currentConfig.contrast = value;
            } else if (key == "SATURATION") {
                currentConfig.saturation = value;
            } else if (key == "AWB_MODE") {
                currentConfig.awbMode = value;
            }
        }
    }

    configFile.close();

    // 验证加载的参数
    if (!validateExposureMode(currentConfig.exposureMode)) {
        currentConfig.exposureMode = defaultConfig.exposureMode;
    }
    if (!validateBrightness(currentConfig.brightness)) {
        currentConfig.brightness = defaultConfig.brightness;
    }
    if (!validateContrast(currentConfig.contrast)) {
        currentConfig.contrast = defaultConfig.contrast;
    }
    if (!validateSaturation(currentConfig.saturation)) {
        currentConfig.saturation = defaultConfig.saturation;
    }
    if (!validateAWBMode(currentConfig.awbMode)) {
        currentConfig.awbMode = defaultConfig.awbMode;
    }

    Utils_Logger::info("Config loaded:");
    Utils_Logger::info("  EXPOSURE_MODE: %d", currentConfig.exposureMode);
    Utils_Logger::info("  BRIGHTNESS: %d", currentConfig.brightness);
    Utils_Logger::info("  CONTRAST: %d", currentConfig.contrast);
    Utils_Logger::info("  SATURATION: %d", currentConfig.saturation);
    Utils_Logger::info("  AWB_MODE: %d", currentConfig.awbMode);

    return true;
}

// 保存配置到文件
bool ISPConfigManager::saveConfig() {
    if (!m_sdCardManager || !m_sdCardManager->isInitialized()) {
        Utils_Logger::error("SD card manager not initialized");
        return false;
    }

    Utils_Logger::info("Saving config to: %s", ISP_CONFIG_FILE_PATH);

    AmebaFatFS* fs = m_sdCardManager->getFileSystem();
    if (!fs) {
        Utils_Logger::error("Failed to get file system");
        return false;
    }

    File configFile = fs->open(ISP_CONFIG_FILE_PATH);
    if (!configFile) {
        Utils_Logger::error("Failed to open config file for writing: %s", ISP_CONFIG_FILE_PATH);
        return false;
    }

    configFile.println("# ISPControl Configuration File");
    configFile.println("# Auto-generated by CameraSystem");
    configFile.println();
    configFile.print("EXPOSURE_MODE=");
    configFile.println(currentConfig.exposureMode);
    configFile.print("BRIGHTNESS=");
    configFile.println(currentConfig.brightness);
    configFile.print("CONTRAST=");
    configFile.println(currentConfig.contrast);
    configFile.print("SATURATION=");
    configFile.println(currentConfig.saturation);
    configFile.print("AWB_MODE=");
    configFile.println(currentConfig.awbMode);

    configFile.close();
    Utils_Logger::info("Config saved successfully");
    return true;
}

// 重置为默认配置
void ISPConfigManager::resetToDefault() {
    currentConfig = defaultConfig;
    Utils_Logger::info("ISP config reset to defaults");
}

// 设置完整配置
void ISPConfigManager::setConfig(const ISPConfig& config) {
    currentConfig = config;
    
    // 验证参数
    if (!validateExposureMode(currentConfig.exposureMode)) {
        currentConfig.exposureMode = defaultConfig.exposureMode;
    }
    if (!validateBrightness(currentConfig.brightness)) {
        currentConfig.brightness = defaultConfig.brightness;
    }
    if (!validateContrast(currentConfig.contrast)) {
        currentConfig.contrast = defaultConfig.contrast;
    }
    if (!validateSaturation(currentConfig.saturation)) {
        currentConfig.saturation = defaultConfig.saturation;
    }
    if (!validateAWBMode(currentConfig.awbMode)) {
        currentConfig.awbMode = defaultConfig.awbMode;
    }
}

// 设置曝光模式
void ISPConfigManager::setExposureMode(int mode) {
    if (validateExposureMode(mode)) {
        currentConfig.exposureMode = mode;
    }
}

// 设置亮度
void ISPConfigManager::setBrightness(int value) {
    if (validateBrightness(value)) {
        currentConfig.brightness = value;
    }
}

// 设置对比度
void ISPConfigManager::setContrast(int value) {
    if (validateContrast(value)) {
        currentConfig.contrast = value;
    }
}

// 设置饱和度
void ISPConfigManager::setSaturation(int value) {
    if (validateSaturation(value)) {
        currentConfig.saturation = value;
    }
}

// 设置白平衡模式
void ISPConfigManager::setAWBMode(int mode) {
    if (validateAWBMode(mode)) {
        currentConfig.awbMode = mode;
    }
}

// 参数验证
bool ISPConfigManager::validateExposureMode(int mode) {
    return (mode >= ISP_EXPOSURE_MODE_MIN && mode <= ISP_EXPOSURE_MODE_MAX);
}

bool ISPConfigManager::validateBrightness(int value) {
    return (value >= ISP_BRIGHTNESS_MIN && value <= ISP_BRIGHTNESS_MAX);
}

bool ISPConfigManager::validateContrast(int value) {
    return (value >= ISP_CONTRAST_MIN && value <= ISP_CONTRAST_MAX);
}

bool ISPConfigManager::validateSaturation(int value) {
    return (value >= ISP_SATURATION_MIN && value <= ISP_SATURATION_MAX);
}

bool ISPConfigManager::validateAWBMode(int mode) {
    return (mode >= ISP_AWB_MODE_MIN && mode <= ISP_AWB_MODE_MAX);
}

// 获取参数标签
const char* ISPConfigManager::getExposureModeLabel(int mode) {
    if (mode == 0) return "手动";
    if (mode == 1) return "自动";
    return "未知";
}

const char* ISPConfigManager::getAWBModeLabel(int mode) {
    if (mode == 0) return "手动";
    if (mode == 1) return "自动";
    return "未知";
}

// 清理资源
void ISPConfigManager::cleanup() {
    Utils_Logger::info("ISPConfigManager cleanup");
    m_sdCardManager = nullptr;
    initialized = false;
}
